---
# Repository-wide Markdownlint configuration
# Conservative line length, but allow tables to exceed the limit because many
# tables in docs contain multiple columns where wrapping inside cells isn't
# desirable. CI uses markdownlint-cli2 and will respect this config.

MD013:
  line_length: 120
  tables: false
  code_blocks: false
